# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module ::Anonymous_Delegator_10; end
module ::Anonymous_Delegator_7; end
module ::Anonymous_Delegator_8; end
module ::Anonymous_Delegator_9; end
module ActiveRecord::Persistence::ActionController::Parameters; end
